### ISSUE TITLE
0.1.5 not found

### ISSUE THREAD

**Issue by ivankennethwang** [tolitius/hface#7]
http://mvnrepository.com/artifact/org.hface/hface-client

I can only see 0.1.4 :) Any reason why it isn't publish yet?

**Comment by tolitius** [comment]
it's is published, and lives along with its Clojure friends in clojars. I think http://mvnrepository.com has several days delay on reporting on artifacts.

you can find it [here](https://clojars.org/repo/org/hface/hface-client/0.1.5/) under https://clojars.org/repo

let me know if you still have problems finding it

**Comment by ivankennethwang** [comment]
Thanks! I'll check again! Closing this for now.
